name: tests

on:
  push:
  pull_request:
  # schedule:
  #   - cron: '0 2 * * *'

env:
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }} Hyperf ${{ matrix.hyperf }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']
        hyperf: ['3.0.*', '3.1.*']
        exclude:
          - php: '8.0'
            hyperf: '3.1.*'
      max-parallel: 20
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: |
          composer require hyperf/di:${{ matrix.hyperf }} --no-update
          composer require hyperf/guzzle:${{ matrix.hyperf }} --no-update
          composer update -o
      - name: Run Cs Fixer
        run: ./vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose --show-progress=dots
      - name: Run Analyse
        run: composer analyse src
      - name: Setup Consul
        run: docker run -d --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 --net=host consul:1.15.4
      - name: Setup Services
        run: |
          docker run -d --name jsonrpc -p 9501:9501 -p 9502:9502 -p 9503:9503 -p 9504:9504 limingxinleo/hyperf-jsonrpc-demo:latest
          sleep 10
          php ./tests/register.php
      - name: Run Test Cases
        run: |
          cp phpunit.xml.dist phpunit.xml
          composer test