name: tests

on: [push, pull_request]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['5.3', '5.4', '5.5', '5.6', '7.0']
      max-parallel: 20
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize, composer:v1
          coverage: none
      - name: Setup Packages
        run: composer update -o
      - name: Run Cs Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Setup Consul
        run: docker run -d --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 --net=host consul:1.15.4
      - name: Setup Services
        run: |
          docker run -d --name jsonrpc -p 9501:9501 -p 9502:9502 -p 9503:9503 -p 9504:9504 limingxinleo/hyperf-jsonrpc-demo:latest
      - name: Register Services
        run: |
          sleep 5
          php ./tests/register.php
      - name: Run Test Cases
        run: |
          composer test