name: tests

on: [push, pull_request]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
      max-parallel: 6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: composer update -o
      - name: Run Cs Fixer
        run: |
          if [ "${{ matrix.php-version }}" == "7.2" ]; then
            echo "Skip php-cs-fixer on PHP 7.2"
          elif [ "${{ matrix.php-version }}" == "7.3" ]; then
            echo "Skip php-cs-fixer on PHP 7.3"
          elif [ "${{ matrix.php-version }}" == "8.2" ]; then
            PHP_CS_FIXER_IGNORE_ENV=true ./vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose --show-progress=dots
          else
            ./vendor/bin/php-cs-fixer fix $1 --dry-run --diff --verbose --show-progress=dots
          fi
      - name: Run Analyse
        run: |
          composer analyse src
      - name: Setup Services
        run: |
          docker run -d --name jsonrpc -p 9501:9501 -p 9502:9502 -p 9503:9503 -p 9504:9504 limingxinleo/hyperf-jsonrpc-demo:latest
          docker run -d --name dev-consul -e CONSUL_BIND_INTERFACE=eth0 --network host consul
          sleep 10
          php ./tests/register.php
      - name: Run Test Cases
        run: |
          cp phpunit.xml.dist phpunit.xml
          composer test